language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
notifications:
  slack:
    secure: "muChTOApEwrBKofsgzo2bkutmFizPihTDgxdzyQbJW/+1Qx086fcBkonbHgFKoW2jEtld1vF1DBEgWbx32dwKpexN+MI6fxcKLLOr/KqdpbCQuliKK69ua4pMbYtkQMThN+GBanFgUKfA3+p5u9tAJ1BQlGm+pTdh6WKdkf5uT+7QW/JIVNzcwLWPcBISzyKGsjxrulgntXtHDC+0/FakS5XNayFUrvS38pntrW0GMzbt3PZLB5T7qPrzvL2k6DnmWAgWKgZ4fK9/QzdjOZyZtO76VSVLDFCQdyxooHR9J042pCOqkH9dEtzwP9uorcCcH6uW81KKL73tVPP0cMMS1VzB0oM3+k91IkLSvEYh0UYbHvmXqTiEjW/zmIutn8+LSbWaydTLezNZ3+wA4KVKaD8O7OAm8+P1KkbPBoh1V4ySIYn8i7vlMCnDFy2sLQEH/OatkIGUDa+Xy/I0Hxc66AXV+hW5kmdZfHFye05PKO7YKv+LyLFsN7dHh4ZosbXezGFlhOLHX2VcQ6Xl1q8Z5UASeLe5mWCzb+xZwGYkpILvNuFX5WEeJFF7B6DI4nWc9jHW5T5YCYMEUluubjyBdyZsUacRxnBPA4LI3Oicp79CwYUZT3cwMk7igRhzNJQHKFsguQFmu2g5zsB3W5Nn8mkDFJuN8kkf1e9cuzT6w4="
script:
  - npm run lint
  - npm test
