/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CalciteAction {
    'active': boolean;
    'indicator': boolean;
    'label': string;
    'text': string;
    'textEnabled': boolean;
  }
  interface CalciteActionBar {
    'expanded': boolean;
  }
  interface CalciteActionGroup {
    'alignBottom': boolean;
    'last': boolean;
  }
  interface CalciteActionPad {}
  interface CalciteTip {
    'header': string;
    'thumbnail': string;
  }
}

declare global {


  interface HTMLCalciteActionElement extends Components.CalciteAction, HTMLStencilElement {}
  var HTMLCalciteActionElement: {
    prototype: HTMLCalciteActionElement;
    new (): HTMLCalciteActionElement;
  };

  interface HTMLCalciteActionBarElement extends Components.CalciteActionBar, HTMLStencilElement {}
  var HTMLCalciteActionBarElement: {
    prototype: HTMLCalciteActionBarElement;
    new (): HTMLCalciteActionBarElement;
  };

  interface HTMLCalciteActionGroupElement extends Components.CalciteActionGroup, HTMLStencilElement {}
  var HTMLCalciteActionGroupElement: {
    prototype: HTMLCalciteActionGroupElement;
    new (): HTMLCalciteActionGroupElement;
  };

  interface HTMLCalciteActionPadElement extends Components.CalciteActionPad, HTMLStencilElement {}
  var HTMLCalciteActionPadElement: {
    prototype: HTMLCalciteActionPadElement;
    new (): HTMLCalciteActionPadElement;
  };

  interface HTMLCalciteTipElement extends Components.CalciteTip, HTMLStencilElement {}
  var HTMLCalciteTipElement: {
    prototype: HTMLCalciteTipElement;
    new (): HTMLCalciteTipElement;
  };
  interface HTMLElementTagNameMap {
    'calcite-action': HTMLCalciteActionElement;
    'calcite-action-bar': HTMLCalciteActionBarElement;
    'calcite-action-group': HTMLCalciteActionGroupElement;
    'calcite-action-pad': HTMLCalciteActionPadElement;
    'calcite-tip': HTMLCalciteTipElement;
  }
}

declare namespace LocalJSX {
  interface CalciteAction extends JSXBase.HTMLAttributes<HTMLCalciteActionElement> {
    'active'?: boolean;
    'indicator'?: boolean;
    'label'?: string;
    'onCalciteActionClick'?: (event: CustomEvent<any>) => void;
    'text'?: string;
    'textEnabled'?: boolean;
  }
  interface CalciteActionBar extends JSXBase.HTMLAttributes<HTMLCalciteActionBarElement> {
    'expanded'?: boolean;
  }
  interface CalciteActionGroup extends JSXBase.HTMLAttributes<HTMLCalciteActionGroupElement> {
    'alignBottom'?: boolean;
    'last'?: boolean;
  }
  interface CalciteActionPad extends JSXBase.HTMLAttributes<HTMLCalciteActionPadElement> {}
  interface CalciteTip extends JSXBase.HTMLAttributes<HTMLCalciteTipElement> {
    'header'?: string;
    'thumbnail'?: string;
  }

  interface IntrinsicElements {
    'calcite-action': CalciteAction;
    'calcite-action-bar': CalciteActionBar;
    'calcite-action-group': CalciteActionGroup;
    'calcite-action-pad': CalciteActionPad;
    'calcite-tip': CalciteTip;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


