/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CalciteAction {
    'active': boolean;
    'disableText': boolean;
    'indicator': boolean;
    'label': string;
  }
  interface CalciteActionBar {
    'expanded': boolean;
  }
  interface CalciteActionGroup {
    'end': boolean;
  }
}

declare namespace LocalJSX {
  interface CalciteAction extends JSXBase.HTMLAttributes {
    'active'?: boolean;
    'disableText'?: boolean;
    'indicator'?: boolean;
    'label'?: string;
    'onCalciteActionClick'?: (event: CustomEvent<any>) => void;
  }
  interface CalciteActionBar extends JSXBase.HTMLAttributes {
    'expanded'?: boolean;
  }
  interface CalciteActionGroup extends JSXBase.HTMLAttributes {
    'end'?: boolean;
  }

  interface IntrinsicElements {
    'calcite-action': CalciteAction;
    'calcite-action-bar': CalciteActionBar;
    'calcite-action-group': CalciteActionGroup;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLCalciteActionElement extends Components.CalciteAction, HTMLStencilElement {}
  var HTMLCalciteActionElement: {
    prototype: HTMLCalciteActionElement;
    new (): HTMLCalciteActionElement;
  };

  interface HTMLCalciteActionBarElement extends Components.CalciteActionBar, HTMLStencilElement {}
  var HTMLCalciteActionBarElement: {
    prototype: HTMLCalciteActionBarElement;
    new (): HTMLCalciteActionBarElement;
  };

  interface HTMLCalciteActionGroupElement extends Components.CalciteActionGroup, HTMLStencilElement {}
  var HTMLCalciteActionGroupElement: {
    prototype: HTMLCalciteActionGroupElement;
    new (): HTMLCalciteActionGroupElement;
  };

  interface HTMLElementTagNameMap {
    'calcite-action': HTMLCalciteActionElement;
    'calcite-action-bar': HTMLCalciteActionBarElement;
    'calcite-action-group': HTMLCalciteActionGroupElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

