/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CalciteAlert {
    'close': () => Promise<void>;
    'color': string;
    'currentAlert': string;
    'dismiss': boolean;
    'duration': string;
    'icon': boolean;
    'id': string;
    'queueLength': number;
    'theme': string;
  }
}

declare namespace LocalJSX {
  interface CalciteAlert extends JSXBase.HTMLAttributes {
    'color'?: string;
    'currentAlert'?: string;
    'dismiss'?: boolean;
    'duration'?: string;
    'icon'?: boolean;
    'id'?: string;
    'onAlertClose'?: (event: CustomEvent<any>) => void;
    'onAlertOpen'?: (event: CustomEvent<any>) => void;
    'queueLength'?: number;
    'theme'?: string;
  }

  interface IntrinsicElements {
    'calcite-alert': CalciteAlert;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLCalciteAlertElement extends Components.CalciteAlert, HTMLStencilElement {}
  var HTMLCalciteAlertElement: {
    prototype: HTMLCalciteAlertElement;
    new (): HTMLCalciteAlertElement;
  };

  interface HTMLElementTagNameMap {
    'calcite-alert': HTMLCalciteAlertElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

